compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: "https://artifacts-read.gkp.jpmchase.net/artifactory/api/npm/npm"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
